{{- if and .Values.bundle.enabled .Values.bundle.tls.caCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opa-service.bundleCASecretName" . }}
  labels:
    {{- include "opa-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: |
    {{- .Values.bundle.tls.caCert | nindent 4 }}
{{- end }}
