{{- if .Values.bundle.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opa-service.bundleAuthSecretName" . }}
  labels:
    {{- include "opa-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  basic-auth: {{ printf "%s:%s" .Values.bundle.auth.username .Values.bundle.auth.deployToken | b64enc | quote }}
{{- end }}
