{{- if and .Values.bundle.enabled (not .Values.bundle.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-chart.bundleAuthSecretName" . }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  basic-auth: {{ printf "%s:%s" .Values.bundle.auth.username .Values.bundle.auth.deployToken | b64enc | quote }}
{{- end }}
