app:
  name: dfx-workflow-enfine

image:
  namespace: atlas
  repository: dfx-workflow-enfine
  pullPolicy: Always

imagePullSecrets:
  - name: dfx-sciwriter-image-pull-secret

pod:
  port: 8080

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http